services:
  server:
    build:
      context: ./ # Use the current directory as the build context
      dockerfile: Dockerfile
    container_name: log
    hostname: log
    volumes:
      - ./:/app
    cap_add:
      - ALL
    privileged: true  # Grant full privileges to the container
    networks:
      printf:
        ipv4_address: 192.168.100.150
    ports:
      - 200:200
    command: sh -c "echo 0 > /proc/sys/kernel/randomize_va_space && tail -f /dev/null"

networks:
  printf:
    ipam:
      config:
        - subnet: 192.168.100.0/24

