version: "3"

services:
  kali:
    build:
      context: . # Use the current directory (where the Dockerfile is located)
      dockerfile: Kali-Dockerfile # Specify the Dockerfile name if it's not the default Dockerfile
    container_name: kali
    hostname: kali
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes
    networks:
      pentest:
        ipv4_address: 192.168.10.100

  target:
    image: tleemcjr/metasploitable2
    container_name: metasploitable2
    hostname: metasploitable2
    tty: true
    cap_add:
      - ALL
    networks:
      pentest:
        ipv4_address: 192.168.10.200

  nessus:
    image: tenable/nessus:latest-ubuntu
    container_name: nessus
    restart: unless-stopped
    ports:
      - "8834:8834" # Web UI and API
    volumes:
      - ./nessus_data:/opt/nessus
    environment:
      - ACCEPT_EULA=YES # Required to accept the EULA
      - USERNAME=admin # Set admin username
      - PASSWORD=mavworks2025 # Set admin password (change it!)
      - ACTIVATION_CODE=YOUR_CODE # Optional for Nessus Pro users
    networks:
      pentest:
        ipv4_address: 192.168.10.50
networks:
  pentest:
    name: pentest
    ipam:
      config:
        - subnet: 192.168.10.0/24
