version: "3"

services:
  attacker:
    build:
      context: . # Use the current directory (where the Dockerfile is located)
      dockerfile: Kali-Dockerfile
    container_name: kali
    hostname: kali
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes
    networks:
      pentest:
        ipv4_address: 192.168.10.100

  victim:
    image: tleemcjr/metasploitable2
    container_name: metasploitable2
    hostname: metasploitable2
    tty: true
    cap_add:
      - ALL
    networks:
      pentest:
        ipv4_address: 192.168.10.200

networks:
  pentest:
    name: pentest
    ipam:
      config:
        - subnet: 192.168.10.0/24
