version: "3.8"

services:
  kali:
    build:
      context: . # Use the current directory (where the Dockerfile is located)
      dockerfile: Kali-Dockerfile # Specify the Dockerfile name if it's not the default Dockerfile
    container_name: kali
    hostname: kali
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes
    networks:
      pentest:
        ipv4_address: 192.168.10.100

  target:
    image: tleemcjr/metasploitable2
    container_name: metasploitable2
    hostname: metasploitable2
    tty: true
    cap_add:
      - ALL
    networks:
      pentest:
        ipv4_address: 192.168.10.200

  nessus:
    build:
      context: . # Use the current directory (where the Dockerfile is located)
      dockerfile: nessus-Dockerfile # Specify the Dockerfile name if it's not the default Dockerfile
    #image: #tenable/nessus:latest-ubuntu
    container_name: nessus
    restart: always
    ports:
      - "8834:8834" # Web UI and API
    environment:
      - ACCEPT_EULA="YES" # Required to accept the EULA
      - USERNAME="admin" # Set admin username
      - PASSWORD="!mavworks2025@1" # FIXME
      - ACTIVATION_CODE="N4FW-79QQ-JEFZ-LZ84-SKGM" # FIXME
    #command: >
    #  sh -c "apt update && apt install -y nessus && /opt/nessus/sbin/nessus-service"
    networks:
      pentest:
        ipv4_address: 192.168.10.50

networks:
  pentest:
    name: pentest
    ipam:
      config:
        - subnet: 192.168.10.0/24
